/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Doctor = IDL.Record({
  'clinic' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Time = IDL.Int;
export const PatientSession = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Opt(Time),
  'doctorId' : IDL.Principal,
  'answers' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
  'language' : IDL.Text,
});

export const idlService = IDL.Service({
  'answerQuestion' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'completeSession' : IDL.Func([IDL.Nat], [], []),
  'createPatientSession' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getDoctor' : IDL.Func([IDL.Principal], [Doctor], ['query']),
  'getPatientSession' : IDL.Func([IDL.Nat], [PatientSession], ['query']),
  'getSessionsByDoctor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PatientSession)],
      ['query'],
    ),
  'registerDoctor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Doctor = IDL.Record({
    'clinic' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const Time = IDL.Int;
  const PatientSession = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Opt(Time),
    'doctorId' : IDL.Principal,
    'answers' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
    'language' : IDL.Text,
  });
  
  return IDL.Service({
    'answerQuestion' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'completeSession' : IDL.Func([IDL.Nat], [], []),
    'createPatientSession' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getDoctor' : IDL.Func([IDL.Principal], [Doctor], ['query']),
    'getPatientSession' : IDL.Func([IDL.Nat], [PatientSession], ['query']),
    'getSessionsByDoctor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PatientSession)],
        ['query'],
      ),
    'registerDoctor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };